apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app
  labels:
    app: kubernetes-app
spec:
  type: ClusterIP 
  ports:
  - port: 8000 
    protocol: TCP
    name: web
  selector:
    app: kubernetes-app

